# Generated by Django 4.0.7 on 2022-10-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0022_alter_event_aims_event_alter_event_concept_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_amount_participants', models.IntegerField(blank=True, default=0, verbose_name='Реальный охват')),
                ('problems', models.TextField(blank=True, max_length=10000, verbose_name='Проблемы при реализации мероприятия')),
                ('need_info', models.BooleanField(default=False, verbose_name='Необходимость в помощи у МК')),
                ('need_external', models.BooleanField(default=False, verbose_name='Необходимость в помощи у КВСК')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='EvaluateOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluate', models.IntegerField(default=1, verbose_name='Оценка организатора в мероприятии')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='student.event', verbose_name='Мероприятие')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='student.event', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка организатора',
                'verbose_name_plural': 'Оценки организаторов',
            },
        ),
    ]
