# Generated by Django 4.0.7 on 2022-10-29 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_evaluateorganizer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluateorganizer',
            name='event',
        ),
        migrations.AddField(
            model_name='evaluateorganizer',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reports.report', verbose_name='Отчет по мероприятию'),
        ),
        migrations.AlterField(
            model_name='report',
            name='need_external',
            field=models.BooleanField(default=False, verbose_name='Потребовалась ли помощь комитета внешних связей и коммуникации при организации мероприятия?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='need_info',
            field=models.BooleanField(default=False, verbose_name='Потребовалась ли помощь медиа комитета при организации мероприятия?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='problems',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Реальные проблемы, возникшие при проведении мероприятия или его организации, и их решения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='real_amount_participants',
            field=models.IntegerField(blank=True, default=0, verbose_name='Реальный охват (кол-во человек)'),
        ),
    ]
