# Generated by Django 4.0.7 on 2022-10-30 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0006_scholarship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'Оценка ПГАС', 'verbose_name_plural': 'Оценки ПГАС'},
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
