# Generated by Django 4.0.7 on 2022-10-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='chat_id',
            field=models.IntegerField(verbose_name='Id чата с пользователем в Telegram'),
        ),
    ]
