# Generated by Django 4.0.7 on 2022-11-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_bot_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id чата с пользователем в Telegram'),
        ),
    ]
