# Generated by Django 4.0.7 on 2022-09-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Уровень доступа')),
            ],
            options={
                'verbose_name': 'Уровень доступа',
                'verbose_name_plural': 'Уровни доступа',
            },
        ),
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название комитеты')),
            ],
            options={
                'verbose_name': 'Комитет',
                'verbose_name_plural': 'Комитеты',
            },
        ),
        migrations.CreateModel(
            name='StatusActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус мероприятия')),
            ],
            options={
                'verbose_name': 'Статус мероприятия',
                'verbose_name_plural': 'Статусы мероприятий',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Учебная группа'),
        ),
        migrations.AddField(
            model_name='profile',
            name='link_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на социальные сети'),
        ),
        migrations.AddField(
            model_name='profile',
            name='link_telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка телеграмм'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.accesslevel', verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.direct', verbose_name='Комитет'),
        ),
    ]
