# Generated by Django 4.0.7 on 2022-09-06 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_accesslevel_direct_statusactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_activity', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('date_activity', models.DateField(blank=True, null=True, verbose_name='Дата проведения мероприятия')),
                ('name_author', models.CharField(blank=True, max_length=100, verbose_name='ФИО главного организатора')),
                ('email_author', models.CharField(blank=True, max_length=100, verbose_name='email главного организатора')),
                ('phone_author', models.CharField(blank=True, max_length=20, verbose_name='Телефонный номер главного организатора')),
                ('aims_activity', models.TextField(blank=True, max_length=1000, verbose_name='Цели мероприятия')),
                ('concept_activity', models.TextField(blank=True, max_length=1000, verbose_name='Концепция мероприятия')),
                ('amount_participants', models.IntegerField(blank=True, default=0, verbose_name='Количество участников')),
                ('place_activity', models.TextField(blank=True, max_length=1000, verbose_name='Место проведения мероприятия')),
                ('need_info', models.BooleanField(default=False, verbose_name='Необходимость в помощи у ИН')),
                ('need_external', models.BooleanField(default=False, verbose_name='Необходимость в помощи у НВСК')),
                ('document_for_info', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на ТЗ для ИН')),
                ('info_uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('document_for_external', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на ТЗ для НВСК')),
                ('external_uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('additional_document', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на дополнительные документы')),
                ('additional_uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('step_one', models.TextField(blank=True, max_length=10000, verbose_name='Подготовка проекта')),
                ('step_two', models.TextField(blank=True, max_length=10000, verbose_name='Реклама')),
                ('step_three', models.TextField(blank=True, max_length=10000, verbose_name='Дистанционный этап')),
                ('step_four', models.TextField(blank=True, max_length=10000, verbose_name='Очный этап')),
                ('step_five', models.TextField(blank=True, max_length=10000, verbose_name='Подведение итогов')),
                ('direct_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.direct', verbose_name='Комитет мероприятия')),
                ('main_organizer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part_list', models.ManyToManyField(blank=True, related_name='part_list', to=settings.AUTH_USER_MODEL)),
                ('queue_list', models.ManyToManyField(blank=True, related_name='queue_list', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.statusactivity', verbose_name='Статус мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
