# Generated by Django 4.0.7 on 2022-09-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_notification_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Event',
        ),
    ]
