# Generated by Django 4.0.7 on 2022-09-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_activity_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='aims_activity',
            new_name='aims_event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='concept_activity',
            new_name='concept_event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_activity',
            new_name='date_event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='direct_activity',
            new_name='direct_event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name_activity',
            new_name='name_event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='place_activity',
            new_name='place_event',
        ),
    ]
