# Generated by Django 4.0.7 on 2022-09-08 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_aims_activity_event_aims_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
