# Generated by Django 4.0.7 on 2022-09-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_event_main_organizer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusActivity',
            new_name='StatusEvent',
        ),
    ]
