# Generated by Django 4.0.7 on 2022-09-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_statusactivity_statusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг пользователя'),
        ),
    ]
