# Generated by Django 4.0.7 on 2022-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_profile_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинговые очки пользователя'),
        ),
    ]
