# Generated by Django 4.0.7 on 2022-10-15 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_event_external_documentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_documentation',
            field=models.BooleanField(default=False, verbose_name='ТЗ для НВСК одобрено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_documentation',
            field=models.BooleanField(default=False, verbose_name='ТЗ для ИН одобрено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='project_documentation',
            field=models.BooleanField(default=False, verbose_name='Папка проекта одобрена'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('data_start_event', models.DateField(blank=True, null=True, verbose_name='Дата начала мероприятия')),
                ('data_end_event', models.DateField(blank=True, null=True, verbose_name='Дата окончания мероприятия')),
                ('list_members', models.TextField(blank=True, max_length=10000, verbose_name='Таблица баллов для всех организаторов')),
                ('amount_participants', models.IntegerField(blank=True, default=0, verbose_name='реальное количество участников')),
                ('problems', models.TextField(blank=True, max_length=10000, verbose_name='Возникшие проблемы')),
                ('need_info', models.BooleanField(default=False, verbose_name='Необходимость в помощи у ИН')),
                ('need_external', models.BooleanField(default=False, verbose_name='Необходимость в помощи у НВСК')),
                ('responsibility', models.BooleanField(default=False, verbose_name='Необходимость в помощи у ИН')),
                ('direct_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.direct', verbose_name='Комитет мероприятия')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.event')),
                ('main_organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
