# Generated by Django 3.2.3 on 2022-10-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_event_external_documentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_documentation',
            field=models.BooleanField(default=False, verbose_name='ТЗ для НВСК одобрено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_documentation',
            field=models.BooleanField(default=False, verbose_name='ТЗ для ИН одобрено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='project_documentation',
            field=models.BooleanField(default=False, verbose_name='Папка проекта одобрена'),
        ),
    ]
