# Generated by Django 4.0.7 on 2022-10-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_event_external_documentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.event'),
        ),
    ]
