# Generated by Django 4.0.7 on 2022-10-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20221010_0139'),
        ('student', '0014_alter_report_event'),
    ]

    operations = [
    ]
