# Generated by Django 4.0.7 on 2022-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_merge_0013_auto_20221010_0139_0014_alter_report_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='id_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id комитеты'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
