# Generated by Django 4.0.7 on 2022-10-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_direct_id_name_delete_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direct',
            options={'verbose_name': 'Комитет', 'verbose_name_plural': 'Комитеты'},
        ),
        migrations.AlterField(
            model_name='direct',
            name='id_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id комитета'),
        ),
        migrations.AlterField(
            model_name='direct',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название комитета'),
        ),
        migrations.AlterField(
            model_name='event',
            name='direct_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.direct', verbose_name='Комитет мероприятия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.direct', verbose_name='Комитет'),
        ),
    ]
