# Generated by Django 4.0.7 on 2022-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_direct_options_alter_direct_id_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Цвет комитета'),
        ),
    ]
