# Generated by Django 4.0.7 on 2022-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_event_main_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего посещения'),
        ),
    ]
