# Generated by Django 4.0.7 on 2022-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mendeleev_bonus',
            field=models.BooleanField(default=False, verbose_name='Добавлено ли в менделеев бонус'),
        ),
    ]
