# Generated by Django 4.0.7 on 2022-10-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_event_mendeleev_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность пользователя'),
        ),
    ]
