# Generated by Django 4.0.7 on 2022-10-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_remove_profile_link_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность пользователя'),
        ),
    ]
